<?php

namespace App\Repository;

/**
 * AvertissementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AvertissementRepository extends \Doctrine\ORM\EntityRepository
{

}
