<?php

namespace App\Repository;

/**
 * Tag_blogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Blog_tagRepository extends \Doctrine\ORM\EntityRepository
{
		public function findAll()
    {
        return $this->findBy(array(),array('title' => 'ASC'));

    }


            public function findByBlog($blog)
    {
        return $this->findBy(array('id_blog' => $blog));

    }

}
