<?php

namespace App\Repository;

/**
 * CandidatReponseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CandidatReponseRepository extends \Doctrine\ORM\EntityRepository
{
}
