<?php

namespace App\Repository;

/**
 * CatalogueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CatalogueRepository extends \Doctrine\ORM\EntityRepository
{


	  public function findByAlias($alias)
    {
        return $this->findOneBy(array('alias' => $alias),array('label' => 'ASC'));

    }
	  public function findByProfil($profil)
    {

        return $this->findBy( [ 'profil' => $profil]) ;

    }
}
