<?php

namespace App\Repository;

/**
 * CataloguefrontRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CataloguefrontRepository extends \Doctrine\ORM\EntityRepository
{
}
