<?php

namespace App\Repository;

/**
 * ContentThemeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContentThemeRepository extends \Doctrine\ORM\EntityRepository
{
  public function findByArchive($etat)
    {
        return $this->findBy(array('archive' => $etat),array('title' => 'ASC'));

    }
}
