<?php

namespace App\Repository;

/**
 * ConventionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConventionRepository extends \Doctrine\ORM\EntityRepository
{
}
