<?php

namespace App\Repository;

/**
 * CvExperienceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CvExperienceRepository extends \Doctrine\ORM\EntityRepository
{
}
