<?php

namespace App\Repository;
use Doctrine\ORM\EntityRepository;

/**
 * DateExceptionnelleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DateExceptionnelleRepository extends EntityRepository
{

    /**
     * Méthode capable de déterminer si la plage de date indiquée existe déjà ou non.
     *
     * @param $options
     * @return bool
     */
    public function isExist($options){
        // Création du QueryBuilder :
        $queryBuilder = $this->createQueryBuilder('d');

        // Récupération des informations :
        $queryBuilder
            ->where($queryBuilder->expr()->eq('d.datedebut', '?1'))
            ->andWhere($queryBuilder->expr()->eq('d.datefin', '?2'))
            ->andWhere($queryBuilder->expr()->neq('d.id', '?3'))

            ->setParameter(1, $options['datedebut'])
            ->setParameter(2, $options['datefin'])
            ->setParameter(3, $options['id'])
        ;

        // Renvoi du résultat :
        return ! empty($queryBuilder->getQuery()->getResult());
    }
}
