<?php

namespace App\Repository;

/**
 * DevisFormationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DevisFormationRepository extends \Doctrine\ORM\EntityRepository
{
}
