<?php

namespace App\Repository;

/**
 * DevisSessionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DevisSessionRepository extends \Doctrine\ORM\EntityRepository
{
}
