<?php

namespace App\Repository;

/**
 * DevisPiedRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DevisPiedRepository extends \Doctrine\ORM\EntityRepository
{
}
