<?php

namespace App\Repository;

/**
 * DossierannexesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DossierannexesRepository extends \Doctrine\ORM\EntityRepository
{
}
