<?php

namespace App\Repository;

/**
 * DossierFormationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DossierFormationRepository extends \Doctrine\ORM\EntityRepository
{
}
