<?php

namespace App\Repository;

/**
 * DossierstageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DossierstageRepository extends \Doctrine\ORM\EntityRepository
{
}
