<?php

namespace App\Repository;

/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepository extends \Doctrine\ORM\EntityRepository
{

		  public function findByArchive($etat)
    {
        return $this->findBy(array('archive' => $etat),array('title' => 'ASC'));

    }
        public function getRang()
    {
        $queryBuilder = $this->createQueryBuilder('f');
        $queryBuilder->select($queryBuilder->expr()->max('f.rang'));
        return (int)$queryBuilder->getQuery()->getScalarResult()[0][1] + 1;
    }

      public function getEventsFromToDay()
    {     
          $now = new \DateTime('now');
          $qb = $this->createQueryBuilder('event')
                    ->where('event.dateevent >= :DATE_NOW')
                    ->setParameter('DATE_NOW', $now)
                    ->orderBy('event.dateevent', 'ASC');
        return $qb->getQuery()->getResult();

    }

    public function findByEventcategory($module,$codemaster,$codelg){

        $qb = $this
            ->createQueryBuilder('e')
            ->join('e.categorie', 'm')
            ->addSelect('m')
            ->leftJoin('m.masterliste', 'l')
            ->addSelect('l')
            ->where('m.code = :codelg and l.module=:module and l.code=:codemaster')
            ->setParameters(array(':codelg'=> $codelg,':module'=>$module,':codemaster'=>$codemaster));
        return $qb->getQuery()->getResult();
    }

    public function getByCategoryevent($module,$codemaster,$codelg){

        $qb = $this
            ->createQueryBuilder('e')
            ->join('e.categorie', 'm')
            ->addSelect('m')
            ->leftJoin('m.masterliste', 'l')
            ->addSelect('l')
            ->where('m.code = :codelg and l.module=:module and l.code=:codemaster')
            ->setParameters(array(':codelg'=> $codelg,':module'=>$module,':codemaster'=>$codemaster));
        return $qb;
    }
}
