<?php

namespace App\Repository;

/**
 * GroupeQuizRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupeQuizRepository extends \Doctrine\ORM\EntityRepository
{
}
