<?php

namespace App\Repository;

/**
 * GroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupRepository extends \NoyauBundle\Repository\ExtendsDoctrineRepository
{
    public function findGroupsByEnabledQueryBuilder($boolEnabled){
        $qb = $this->createQueryBuilder('g');
        $qb->select('g')
            ->where($qb->expr()->eq('g.enabled', '?1'))
            ->setParameter(1, $boolEnabled);

        return $qb;
    }

    public function findGroupsByEnabled($boolEnabled){

        return $this->findGroupsByEnabledQueryBuilder($boolEnabled)->getQuery()->getResult();
    }
}
