<?php

namespace App\Repository;

/**
 * HistoriqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HistoriqueRepository extends \Doctrine\ORM\EntityRepository
{


 public function findByField($search)
    {
		$qb = $this
			->createQueryBuilder('historique')
			->where('historique.field = :SEARCH_REQUEST')
			->setParameter('SEARCH_REQUEST', $search)
             ->setMaxResults(1);
		return $qb->getQuery()->getOneOrNullResult();


    }


	   


}
