<?php

namespace App\Repository;

/**
 * HistoriqueemailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HistoriqueemailRepository extends \Doctrine\ORM\EntityRepository
{
}
