<?php

namespace App\Repository;

/**
 * Image_blogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Image_blogRepository extends \Doctrine\ORM\EntityRepository
{
}
