<?php

namespace App\Repository;

/**
 * IpconfigRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IpconfigRepository extends \Doctrine\ORM\EntityRepository
{
}
