<?php

namespace App\Repository;

/**
 * MenuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MenuRepository extends \Doctrine\ORM\EntityRepository
{
	  public function findByArchive($etat)
    {
        return $this->findBy(array('archive' => $etat),array('label' => 'ASC'));

    }


          public function getMenuBytype($type)
    {
        $qb = $this
      ->createQueryBuilder('menu')
            ->join('menu.type', 'type')
            ->addSelect('type')
            ->where('type.valeur = :valeur')
            ->setParameter('valeur', $type)
            ->orderBy('menu.rang');
    return $qb;

    }
	      public function findMenuBytype($type)
    {
        $qb = $this
      ->createQueryBuilder('menu')
            ->join('menu.type', 'type')
            ->addSelect('type')
            ->where('type.valeur = :valeur')
            ->setParameter('valeur', $type)
            ->orderBy('menu.rang');
        return $qb->getQuery()->getResult();

    }
        public function getRang()
    {
        $queryBuilder = $this->createQueryBuilder('f');
        $queryBuilder->select($queryBuilder->expr()->max('f.rang'));
        return (int)$queryBuilder->getQuery()->getScalarResult()[0][1] + 1;
    }
}
