<?php

namespace App\Repository;

/**
 * MenuContentPageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MenuContentPageRepository extends \Doctrine\ORM\EntityRepository
{
	  public function findByArchive($etat)
    {
        return $this->findBy(array('archive' => $etat),array('label' => 'ASC'));

    }

      public function findByMenu($menu)
    {
        return $this->findBy(array('menu' => $menu),array('rang' => 'ASC'));

    }

	
        public function getRang()
    {
        $queryBuilder = $this->createQueryBuilder('f');
        $queryBuilder->select($queryBuilder->expr()->max('f.rang'));
        return (int)$queryBuilder->getQuery()->getScalarResult()[0][1] + 1;
    }
      public function getBymenuIdentifiant($menuIdentifiant)
    {

        $qb = $this->createQueryBuilder('pagemenu')
                    ->innerJoin('pagemenu.menu', 'menu')
                    ->where('menu.name = :NAME')
                    ->setParameter('NAME', $menuIdentifiant)
                 ->addOrderBy('pagemenu.rang', 'ASC');
        return $qb->getQuery()->getResult();
    }

}
