<?php

namespace App\Repository;

/**
 * ModuleContratRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModuleContratRepository extends \Doctrine\ORM\EntityRepository
{
}
