<?php

namespace App\Repository;

/**
 * NiveausocialRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NiveausocialRepository extends \Doctrine\ORM\EntityRepository
{
}
