<?php

namespace App\Repository;

/**
 * OfferRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OfferRepository extends \Doctrine\ORM\EntityRepository
{

		  public function findByArchive($etat)
    {
        return $this->findBy(array('archive' => $etat),array('title' => 'ASC'));

    }
        public function getRang()
    {
        $queryBuilder = $this->createQueryBuilder('f');
        $queryBuilder->select($queryBuilder->expr()->max('f.rang'));
        return (int)$queryBuilder->getQuery()->getScalarResult()[0][1] + 1;
    }


    public function getByoffresAlternance($offres_alternance){
        $qb = $this
                ->createQueryBuilder()
                ->select('offre')
                ->from('NoyauBundle:Offre', 'offre')
                ->where('offre.etat = :ETAT')
                ->andwhere('offre NOT IN (:ALTRNANCE)')
                ->setParameter('ETAT', 1)
                ->setParameter('ALTRNANCE', $offres_alternance)
                ->orderBy('offre.id', 'DESC');
        return $qb->getQuery()->getResult();
    }

    
}
