<?php

namespace App\Repository;

/**
 * OfferCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OfferCategoryRepository extends \Doctrine\ORM\EntityRepository
{
		public function findAll()
    {
        return $this->findBy(array(),array('name' => 'ASC'));

    }
        public function getRang()
    {
        $queryBuilder = $this->createQueryBuilder('f');
        $queryBuilder->select($queryBuilder->expr()->max('f.rang'));
        return (int)$queryBuilder->getQuery()->getScalarResult()[0][1] + 1;
    }
}
