<?php

namespace App\Repository;

/**
 * PageSectionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PageSectionRepository extends \Doctrine\ORM\EntityRepository
{
}
