<?php

namespace App\Repository;

/**
 * PartnerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PartnerRepository extends \Doctrine\ORM\EntityRepository
{

		  public function findByArchive($etat)
    {
        return $this->findBy(array('archive' => $etat),array('name' => 'ASC'));

    }
        public function getRang()
    {
        $queryBuilder = $this->createQueryBuilder('f');
        $queryBuilder->select($queryBuilder->expr()->max('f.rang'));
        return (int)$queryBuilder->getQuery()->getScalarResult()[0][1] + 1;
    }


          public function getPageFilsByParentId($idparent,$visibility)
    {
            
                $qb = $this->createQueryBuilder('partner')
                    ->where('page.parent = :PAGE_PARENT')
                    ->Andwhere('page.visibility = :visibility')
                    ->innerJoin('partner.partnercategory', 'categorie')
                    ->where('partner.archive = :ARCHIVE')
                    ->setParameter('ARCHIVE', $visibility);
        return $qb->getQuery()->getResult();


    }

}
