<?php

namespace App\Repository;

/**
 * PdfcatalogueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PdfcatalogueRepository extends \Doctrine\ORM\EntityRepository
{
}
