<?php

namespace App\Repository;

/**
 * PersonneDocumentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersonneDocumentRepository extends \Doctrine\ORM\EntityRepository
{
   
}
