<?php

namespace App\Repository;

/**
 * ProspectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProspectRepository extends \Doctrine\ORM\EntityRepository
{


	public function findByDossiertypeactif($typeactif){

		$qb = $this
			->createQueryBuilder('p')
            ->join('p.dossier', 'd')
            ->addSelect('d')
            ->where('d.typeactif = :typeactif')
            ->setParameters(array(':typeactif'=> $typeactif));
		return $qb->getQuery()->getResult();
	}


}
