<?php

namespace App\Repository;


/**
 * QuestionQuizRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestionQuizRepository extends \Doctrine\ORM\EntityRepository
{

 public function isDoublon($valeursConditions, $signesConditions){

        // Création du QueryBuilder :
        $queryBuilder = $this->createQueryBuilder('n');

        // Récupération des informations :
        $i = 0;
        foreach ($valeursConditions as $key => $value) {
            if ($i == 0) {
                $queryBuilder->where('n.' . $key . ' ' . $signesConditions[$i] . ' :' . $key);
            }else{
                $queryBuilder->andWhere('n.' . $key . ' ' . $signesConditions[$i] . ' :' . $key);
            }
            ++$i;
        }

        // Renvoi du résultat :
        return ! empty($queryBuilder
            ->setParameters($valeursConditions)
            ->getQuery()
            ->getResult());
    }
}
