<?php

namespace App\Repository;


/**
 * QuestionGroupeQuizRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestionGroupeQuizRepository extends \Doctrine\ORM\EntityRepository
{
}
