<?php

namespace App\Repository;

/**
 * RechercheFormRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RechercheFormRepository extends \Doctrine\ORM\EntityRepository
{
	
	
	public function getByEmploye($employe)
	{
		$qb = $this->createQueryBuilder("r")
			->where(':employe MEMBER OF r.portailemployes')
			->setParameters(array('employe' => $employe))
		;
		return $qb->getQuery()->getResult();
	}
}
