<?php

namespace App\Repository;

/**
 * ReponseTextRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReponseTextRepository extends \Doctrine\ORM\EntityRepository
{
}
