<?php

namespace App\Repository;

/**
 * ReponseMultipleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReponseMultipleRepository extends \Doctrine\ORM\EntityRepository
{
}
