<?php

namespace App\Repository;

/**
 * SessionFormationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SessionFormationRepository extends \Doctrine\ORM\EntityRepository
{
}
