<?php

namespace App\Repository;

/**
 * SessionModuleEnchainementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SessionModuleEnchainementRepository extends \Doctrine\ORM\EntityRepository
{
}
