<?php

namespace App\Repository;

/**
 * SidebarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SidebarRepository extends \Doctrine\ORM\EntityRepository
{
}
