<?php

namespace App\Repository;

/**
 * SousThemeQuizRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SousThemeQuizRepository extends \Doctrine\ORM\EntityRepository
{
}
