<?php

namespace App\Repository;

/**
 * StatutJuridiqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StatutJuridiqueRepository extends \Doctrine\ORM\EntityRepository
{
}
