<?php

namespace App\Repository;
use Doctrine\ORM\EntityRepository;

/**
 * TacheHistoriqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TacheHistoriqueRepository extends EntityRepository
{
 
}
