<?php

namespace App\Repository;

/**
 * TagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagRepository extends \Doctrine\ORM\EntityRepository
{

    protected $tag;
    public function __construct(Tag $tag)

	{
		$this->tag = $tag;
	}
		public function findAll()
    {
        return $this->findBy(array(),array('title' => 'ASC'));

    }


}
