<?php

namespace App\Repository;

/**
 * TarifVenteIntraJourRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TarifVenteIntraJourRepository extends \Doctrine\ORM\EntityRepository
{
}
