<?php

namespace App\Repository;

/**
 * ThemeQuizRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ThemeQuizRepository  extends \NoyauBundle\Repository\ExtendsDoctrineRepository
{
}
