<?php

namespace App\Repository;

/**
 * TiersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TiersRepository extends \Doctrine\ORM\EntityRepository
{
}
