<?php

namespace App\Repository;

/**
 * namespace QuizBundle\Form;
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeQuestionRepository extends \Doctrine\ORM\EntityRepository
{
}
