<?php

namespace App\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends ExtendsDoctrineRepository
{
    public function findUsersByEnabled($boolEnabled){
        $qb = $this->createQueryBuilder('u');
        $qb->select('u')
            ->where($qb->expr()->eq('u.enabled', '?1'))
            ->setParameter(1, $boolEnabled);

        return $qb->getQuery()->getResult();
    }

    public function findByRole($role)
{
    $qb = $this->_em->createQueryBuilder();
    $qb->select('u')
        ->from($this->_entityName, 'u')
        ->leftJoin('u.groups', 'g')
        ->where($qb->expr()->orX(
            $qb->expr()->like('u.roles', ':roles'),
            $qb->expr()->like('g.roles', ':roles')
        ))
        ->setParameter('roles', '%"'.$role.'"%');

    return $qb->getQuery()->getResult();
}

}
