<?php

namespace App\Repository;

/**
 * VrReunionParticipantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VrReunionParticipantRepository extends \Doctrine\ORM\EntityRepository
{

	public function getGroupeForReunion($reunion)
	{
		$resultat=[];
		$sql="
			SELECT user_email,
				sum(duree)
			FROM vrreunionparticipants 
			WHERE vrreunion_id=".$reunion->getId()."
			GROUP BY user_email;
		";

		$conn = $this->_em->getConnection();
		$statement = $conn->executeQuery($sql);
		$resultat = $statement->fetchAll();
		
		return $resultat;
	}

}
