<?php

namespace App\Repository;

/**
 * VrReunionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VrReunionRepository extends \Doctrine\ORM\EntityRepository
{

	public function getBetweenDates($debut,$fin)
	{
        $resultat = $this->createQueryBuilder('v')
			->where('v.debut >= :debut')
			->andWhere('v.fin <= :fin')
			->setParameter('debut', $debut)
			->setParameter('fin', $fin)
			->getQuery()->getResult();
		return $resultat;
	}

}
